jobs:
- job: VS2019
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      MSBuild.exe noexcept_inline_DLL_benchmark.sln -p:Platform=x64 -p:Configuration=Release_use_noexcept
      MSBuild.exe noexcept_inline_DLL_benchmark.sln -p:Platform=x64 -p:Configuration=Release_without_noexcept
    displayName: Build with and without noexcept 
  - script: |
      type test_exe\x64\Release_use_noexcept\test_main.cod
    displayName: ASM using noexcept
  - script: |
      type test_exe\x64\Release_without_noexcept\test_main.cod
    displayName: ASM without noexcept
  - script: |
      call x64\Release_use_noexcept\test_exe.exe
    displayName: Run using noexcept
  - script: |
      call x64\Release_without_noexcept\test_exe.exe
    displayName: Run without noexcept

- job: VS2017
  pool:
    vmImage: 'VS2017-Win2016'
  steps:
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      MSBuild.exe noexcept_inline_DLL_benchmark.sln -p:Platform=x64;PlatformToolset=v141;WindowsTargetPlatformVersion=10.0.14393.0;Configuration=Release_use_noexcept
      MSBuild.exe noexcept_inline_DLL_benchmark.sln -p:Platform=x64;PlatformToolset=v141;WindowsTargetPlatformVersion=10.0.14393.0;Configuration=Release_without_noexcept
    displayName: Build with and without noexcept 
  - script: |
      type test_exe\x64\Release_use_noexcept\test_main.cod
    displayName: ASM using noexcept
  - script: |
      type test_exe\x64\Release_without_noexcept\test_main.cod
    displayName: ASM without noexcept
  - script: |
      call x64\Release_use_noexcept\test_exe.exe
    displayName: Run using noexcept
  - script: |
      call x64\Release_without_noexcept\test_exe.exe
    displayName: Run without noexcept

